services:
  web:
    build:
      context: .
    ports:
      - "8080:80" # Expose le conteneur sur le port 8080
    volumes:
      - ./:/var/www/html # Montez le code source pour le développement
    container_name: mon-cv-numerique
